// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbcn842kxuCJKEDcQhVWUA2ZWdCEC_I3c',
    appId: '1:347156798890:web:aef061e17b3f3d26171fd3',
    messagingSenderId: '347156798890',
    projectId: 'hobin-46b56',
    authDomain: 'hobin-46b56.firebaseapp.com',
    storageBucket: 'hobin-46b56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtpRv70TgK0FhOKEpqHYRZUSkKDDJZPqw',
    appId: '1:347156798890:android:226dfcd506895326171fd3',
    messagingSenderId: '347156798890',
    projectId: 'hobin-46b56',
    storageBucket: 'hobin-46b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAODakcxCIakSp4Ccu6k_Dx7RhwNs2rGWk',
    appId: '1:347156798890:ios:50d5824d37470000171fd3',
    messagingSenderId: '347156798890',
    projectId: 'hobin-46b56',
    storageBucket: 'hobin-46b56.appspot.com',
    androidClientId: '347156798890-e6nbmr5qodah494qdjl05lbf1ri0noor.apps.googleusercontent.com',
    iosClientId: '347156798890-mb5e4385avqdesvhkomgc4av73li754e.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAODakcxCIakSp4Ccu6k_Dx7RhwNs2rGWk',
    appId: '1:347156798890:ios:50d5824d37470000171fd3',
    messagingSenderId: '347156798890',
    projectId: 'hobin-46b56',
    storageBucket: 'hobin-46b56.appspot.com',
    androidClientId: '347156798890-e6nbmr5qodah494qdjl05lbf1ri0noor.apps.googleusercontent.com',
    iosClientId: '347156798890-mb5e4385avqdesvhkomgc4av73li754e.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobinApp',
  );
}
